[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "mcap"
version = "0.1.0"
description = "MCAP: Monte Carlo adjusted profile."
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "ChaosDonkey06" }]
license = { file = "LICENSE" }

[tool.setuptools.packages.find]
where = ["."]
include = ["mcap*"]
